package com.google.android.gms.ads.internal;

import android.content.pm.ApplicationInfo;
import android.content.pm.PackageInfo;
import android.location.Location;
import android.os.Bundle;
import com.google.android.gms.internal.ads.zzaef;
import com.google.android.gms.internal.ads.zzaeg;
import com.google.android.gms.internal.ads.zzaji;
import com.google.android.gms.internal.ads.zzang;
import com.google.android.gms.internal.ads.zzano;
import com.google.android.gms.internal.ads.zzjj;
import com.google.android.gms.internal.ads.zzjn;
import com.google.android.gms.internal.ads.zzlu;
import com.google.android.gms.internal.ads.zzmq;
import com.google.android.gms.internal.ads.zznx;
import com.google.android.gms.internal.ads.zzpb;
import com.google.android.gms.internal.ads.zzpl;
import java.util.List;
import java.util.concurrent.Callable;
import org.json.JSONArray;
import org.json.JSONObject;

final class zzbe implements Callable<zzpb> {
    private final /* synthetic */ zzbc zzaaf;
    private final /* synthetic */ int zzaag;
    private final /* synthetic */ JSONArray zzaah;
    private final /* synthetic */ int zzaai;
    private final /* synthetic */ zzaji zzwg;

    zzbe(zzbc zzbc, int i, JSONArray jSONArray, int i2, zzaji zzaji) {
        this.zzaaf = zzbc;
        this.zzaag = i;
        this.zzaah = jSONArray;
        this.zzaai = i2;
        this.zzwg = zzaji;
    }

    public final /* synthetic */ Object call() throws Exception {
        if (this.zzaag >= this.zzaah.length()) {
            return null;
        }
        JSONArray jSONArray = new JSONArray();
        jSONArray.put(this.zzaah.get(this.zzaag));
        JSONObject jSONObject = new JSONObject();
        jSONObject.put("ads", jSONArray);
        zzbc zzbc = new zzbc(this.zzaaf.zzvw.zzrt, this.zzaaf.zzwc, this.zzaaf.zzvw.zzacv, this.zzaaf.zzvw.zzacp, this.zzaaf.zzwh, this.zzaaf.zzvw.zzacr, true);
        zzbc.zza(this.zzaaf.zzvw, zzbc.zzvw);
        zzbc.zzdq();
        zzbc.zza(this.zzaaf.zzvs);
        zznx zznx = zzbc.zzvr;
        int i = this.zzaag;
        zznx.zze("num_ads_requested", String.valueOf(this.zzaai));
        zznx.zze("ad_index", String.valueOf(i));
        zzaef zzaef = this.zzwg.zzcgs;
        String jSONObject2 = jSONObject.toString();
        Bundle bundle = zzaef.zzccv.extras != null ? new Bundle(zzaef.zzccv.extras) : new Bundle();
        bundle.putString("_ad", jSONObject2);
        int i2 = zzaef.zzccv.versionCode;
        long j = zzaef.zzccv.zzapw;
        int i3 = zzaef.zzccv.zzapx;
        List<String> list = zzaef.zzccv.zzapy;
        boolean z = zzaef.zzccv.zzapz;
        int i4 = zzaef.zzccv.zzaqa;
        boolean z2 = zzaef.zzccv.zzaqb;
        String str = zzaef.zzccv.zzaqc;
        zzmq zzmq = zzaef.zzccv.zzaqd;
        Location location = zzaef.zzccv.zzaqe;
        String str2 = zzaef.zzccv.zzaqf;
        zzmq zzmq2 = zzmq;
        String str3 = str2;
        zzjj zzjj = new zzjj(i2, j, bundle, i3, list, z, i4, z2, str, zzmq2, location, str3, zzaef.zzccv.zzaqg, zzaef.zzccv.zzaqh, zzaef.zzccv.zzaqi, zzaef.zzccv.zzaqj, zzaef.zzccv.zzaqk, zzaef.zzccv.zzaql);
        Bundle bundle2 = zzaef.zzccu;
        zzjn zzjn = zzaef.zzacv;
        String str4 = zzaef.zzacp;
        ApplicationInfo applicationInfo = zzaef.applicationInfo;
        PackageInfo packageInfo = zzaef.zzccw;
        String str5 = zzaef.zzccy;
        String str6 = zzaef.zzccz;
        zzang zzang = zzaef.zzacr;
        Bundle bundle3 = zzaef.zzcda;
        List<String> list2 = zzaef.zzads;
        List<String> list3 = zzaef.zzcdk;
        Bundle bundle4 = zzaef.zzcdc;
        boolean z3 = zzaef.zzcdd;
        int i5 = zzaef.zzcde;
        int i6 = zzaef.zzcdf;
        float f = zzaef.zzagu;
        String str7 = zzaef.zzcdg;
        Bundle bundle5 = bundle3;
        List<String> list4 = list2;
        long j2 = zzaef.zzcdh;
        String str8 = zzaef.zzcdi;
        List<String> list5 = zzaef.zzcdj;
        String str9 = zzaef.zzaco;
        zzpl zzpl = zzaef.zzadj;
        String str10 = zzaef.zzcdm;
        float f2 = zzaef.zzcdn;
        boolean z4 = zzaef.zzcdt;
        int i7 = zzaef.zzcdo;
        int i8 = zzaef.zzcdp;
        boolean z5 = zzaef.zzcdq;
        boolean z6 = zzaef.zzcdr;
        Bundle bundle6 = bundle4;
        zzany zzi = zzano.zzi(zzaef.zzcds);
        String str11 = zzaef.zzcdu;
        boolean z7 = z6;
        boolean z8 = zzaef.zzbss;
        int i9 = zzaef.zzcdv;
        Bundle bundle7 = zzaef.zzcdw;
        String str12 = zzaef.zzcdx;
        zzlu zzlu = zzaef.zzadl;
        boolean z9 = zzaef.zzcdy;
        Bundle bundle8 = zzaef.zzcdz;
        List<String> list6 = list3;
        zzjj zzjj2 = zzjj;
        PackageInfo packageInfo2 = packageInfo;
        String str13 = str5;
        String str14 = str6;
        zzang zzang2 = zzang;
        Bundle bundle9 = bundle5;
        List<String> list7 = list4;
        boolean z10 = z3;
        int i10 = i5;
        int i11 = i6;
        float f3 = f;
        String str15 = str7;
        long j3 = j2;
        String str16 = str8;
        List<String> list8 = list5;
        String str17 = str9;
        zzpl zzpl2 = zzpl;
        String str18 = str10;
        float f4 = f2;
        boolean z11 = z4;
        int i12 = i7;
        int i13 = i8;
        boolean z12 = z5;
        boolean z13 = z7;
        zzbc zzbc2 = zzbc;
        zzbc2.zza(new zzaeg(bundle2, zzjj2, zzjn, str4, applicationInfo, packageInfo2, str13, str14, zzang2, bundle9, list7, list6, bundle6, z10, i10, i11, f3, str15, j3, str16, list8, str17, zzpl2, str18, f4, z11, i12, i13, z12, z13, zzi, str11, z8, i9, bundle7, str12, zzlu, z9, bundle8, zzaef.zzced, zzano.zzi(zzaef.zzccx), zzaef.zzadn, zzaef.zzcee, zzaef.zzcef, 1, zzaef.zzceh, zzaef.zzcei, zzaef.zzcej, zzaef.zzcek), zzbc2.zzvr);
        return zzbc2.zzds().get();
    }
}
